# Generated by Django 2.1.9 on 2020-02-15 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_auto_20200214_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
