# Generated by Django 2.1.9 on 2020-02-17 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_auto_20200215_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
